### ISSUE TITLE
Core async, channel gets filled up

### ISSUE THREAD

**Issue by hlolli** [rksm/subprocess#1]
Hi, thanks for this nice tool. After running it for a while, I get an error that the channel is filled up

```
Exception in thread "async-dispatch-5" 
java.lang.AssertionError: Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
(< (.size puts) impl/MAX-QUEUE-SIZE)
	at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:152)
	at clojure.core.async$put_BANG_.invokeStatic(async.clj:164)
	at clojure.core.async$put_BANG_.invoke(async.clj:157)
	at rksm.subprocess$capture_stream$fn__21227$state_machine__18458__auto____21234$fn__21236$fn__21238.invoke(subprocess.clj:14)
	at rksm.subprocess$capture_stream$fn__21227$state_machine__18458__auto____21234$fn__21236.invoke(subprocess.clj:11)
	at rksm.subprocess$capture_stream$fn__21227$state_machine__18458__auto____21234.invoke(subprocess.clj:11)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at rksm.subprocess$capture_stream$fn__21227.invoke(subprocess.clj:11)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I'm guessing the app is collecting some stdout/stderr messages that I'm ignoring. Maybe using a drop last buffer could be good in those cases?

**Comment by hlolli** [comment]
this isn't so much of a bug, as I'm not consuming the returned channel. So I close this :)
